get http://localhost:4000/user-api/users

###
get http://localhost:4000/user-api/users/100

###
post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "username":"ravi",
    "password":"manoj",
    "email":"manoj@mail.com"
}


###
post http://localhost:4000/user-api/user-login
Content-Type: application/json

{
    "username":"kiran",
    "password":"kiran"
   
}

###
get http://localhost:4000/user-api/protected
Authorization: Bearer eJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmFuIiwiaWF0IjoxNzA3MzY5MzIyLCJleHAiOjE3MDczNjkzNDJ9.SnQ8oJWufC0vp7X2wIaISFr8_YRaNAxpmvJF9t6kKZk


###
put http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userId":100,
    "name":"suresh kumar"
}

###
delete http://localhost:4000/user-api/user/200

###
get http://localhost:4000/product-api/products